### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by dfkki123508** [CitrusPunk/CellularAutomaton#1]
Looking at the code I see heap-allocated variables  which are not free'd, e.g. [here](https://github.com/CitrusPunk/cellular-automaton/blob/master/gameOfLife.cpp#L141).  Valgrind should detect it.

**Comment by CitrusPunk** [comment]
Thanks, for your feedback. You are totally right.
This is an old project that isn't maintained anymore.

Feel free to make a pull request though.
